### ISSUE TITLE
Creo que este modulo em está impidiendo lanzar un script desde terminal

### ISSUE THREAD

**Issue by JohnnyVM** [Comunitea/external_ecommerce_modules#5]
Buenas
Intento lanzar el script  AutoRefresh Web visibility que hay en acciones planificadas  mediante una terminal python_odoo  para actualizar la visibilidad de los productos en la página y me salta el fallo:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/odoo/anzamar/project-addons/scheduled_sale/models/product_template.py", line 28, in write
    return super(ProductTemplate, self).write(vals)
  File "/opt/odoo/anzamar/odoo-repos/external_ecommerce/seo_base/models/product.py", line 56, in write
    'slug': record._slug_validation(new_slug)
  File "/opt/odoo/anzamar/odoo-repos/external_ecommerce/seo_base/models/product.py", line 25, in _slug_validation
    host = request.httprequest.host.split(':')[0]
  File "/opt/odoo/anzamar/eggs/Werkzeug-0.11.11-py3.6.egg/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/opt/odoo/anzamar/eggs/Werkzeug-0.11.11-py3.6.egg/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/opt/odoo/anzamar/eggs/Werkzeug-0.11.11-py3.6.egg/werkzeug/local.py", line 135, in _lookup
    raise RuntimeError('object unbound')

Creo que el fallo está relacionado con algo como esto:
https://github.com/odoo/odoo/commit/10c1187e7bdd12c26db6bf8bb19aa1dc0b4d6634

Aqui se esta llamando directamente a request sin hacer ninguna comprobación
https://github.com/Comunitea/external_ecommerce_modules/blob/11.0/seo_base/models/product.py
Linea 25, como no estoy en una página web salta el error
Tampoco tengo muy claro que intentais hacer con el módulo (ni idea que significa SLUG) como para proponer una solución

**Comment by neo-oien** [comment]
Hice un commit con nueva comporbación si hay una website.
Si no hay ninguna, meterá una por defecto.

**Comment by JohnnyVM** [comment]
Gracias
